import { DEFAULTS } from '.opencode/plugins/core/constants';
import type { UserEventsConfig } from '.opencode/plugins/types/config';

export const defaultUserConfig: UserEventsConfig = {
  enabled: true,
  logDisabledEvents: false,
  showPluginStatus: true,
  pluginStatusDisplayMode: 'user-only',
  toastQueue: {
    staggerMs: 300,
    maxSize: 50,
  },
  loadClaudeHookSettings: {
    loadGlobalClaudeHooks: true,
    loadLocalClaudeHooks: true,
  },
  scriptToasts: {
    showOutput: true,
    showError: true,
    outputVariant: 'warning',
    errorVariant: 'error',
    outputDuration: 5000,
    errorDuration: 15000,
    outputTitle: '- SCRIPTS OUTPUT',
    errorTitle: '- SCRIPT ERROR',
  },
  default: {
    toast: false,
    runScripts: false,
    runOnlyOnce: false,
    logToAudit: true,
    appendToSession: false,
  },
  audit: {
    enabled: true,
    level: 'debug',
    basePath: './opencode-hooks/logs',
    maxSizeMB: 1,
    maxAgeDays: 30,
    logTruncationKB: 2,
    maxFieldSize: 1000,
    maxArrayItems: 50,
    largeFields: [
      'patch',
      'diff',
      'content',
      'snapshot',
      'output',
      'result',
      'text',
    ],
    files: DEFAULTS.audit.files,
  },
  events: {
    'command.executed': { enabled: false },
    'file.edited': { enabled: false },
    'file.watcher.updated': { enabled: false },
    'vcs.branch.updated': { enabled: false },
    'installation.updated': { enabled: false },
    'installation.update-available': { enabled: false },
    'lsp.client.diagnostics': { enabled: false },
    'lsp.updated': { enabled: false },
    'message.part.removed': { enabled: false },
    'message.part.updated': { enabled: false },
    'message.removed': { enabled: false },
    'message.updated': { enabled: false },
    'permission.updated': { enabled: false },
    'permission.replied': { enabled: false },
    'server.connected': { enabled: false },
    'server.instance.disposed': { enabled: false },
    'session.created': { enabled: false },
    'session.compacted': { enabled: false },
    'session.deleted': { enabled: false },
    'session.diff': { enabled: false },
    'session.error': { enabled: false },
    'session.idle': { enabled: false },
    'session.status': { enabled: false },
    'session.updated': { enabled: false },
    'todo.updated': { enabled: false },
    'shell.env': { enabled: false },
    'tool.execute.after': { enabled: false },
    'tool.execute.after.subagent': { enabled: false },
    'tool.execute.before': { enabled: false },
    'tool.execute.before.subagent': { enabled: false },
    'tui.prompt.append': { enabled: false },
    'tui.command.execute': { enabled: false },
    'tui.toast.show': { enabled: false },
    'pty.created': { enabled: false },
    'pty.updated': { enabled: false },
    'pty.exited': { enabled: false },
    'pty.deleted': { enabled: false },
    'message.part.delta': { enabled: false },
    'permission.asked': { enabled: false },
    'permission.ask': { enabled: false },
    'command.execute.before': { enabled: false },
    'experimental.session.compacting': { enabled: false },
    'chat.message': { enabled: false },
    'chat.params': { enabled: false },
    'chat.headers': { enabled: false },
    'experimental.chat.messages.transform': { enabled: false },
    'experimental.chat.system.transform': { enabled: false },
    'experimental.text.complete': { enabled: false },
    'tool.definition': { enabled: false },
    'session.unknown': { enabled: false },
  },
  tools: {
    'tool.execute.after': {},
    'tool.execute.after.subagent': {},
    'tool.execute.before': {},
    'tool.execute.before.subagent': {},
  },
};
