import type { UserEventsConfig } from '.opencode/plugins/types/config';

export const userConfig: UserEventsConfig = {
  enabled: true,
  logDisabledEvents: false,
  showPluginStatus: false,
  pluginStatusDisplayMode: 'user-only',
  loadClaudeHookSettings: { enabled: false },
  scriptToasts: {
    showOutput: true,
    showError: true,
    outputVariant: 'warning',
    errorVariant: 'error',
    outputDuration: 5000,
    errorDuration: 15000,
    outputTitle: '- SCRIPTS OUTPUT',
    errorTitle: '- SCRIPT ERROR',
  },
  default: {
    debug: false,
    toast: false,
    runScripts: false,
    runOnlyOnce: false,
    logToAudit: true,
    appendToSession: false,
  },
  audit: {
    enabled: true,
    level: 'debug',
    basePath: '/tmp/test-audit',
    maxSizeMB: 1,
    maxAgeDays: 7,
    logTruncationKB: 1,
    maxFieldSize: 100,
    maxArrayItems: 10,
    largeFields: [],
    sessionId: 'test',
    files: [],
    archiveDir: '',
  },
  events: {},
  tools: {},
};
